version: '3'

services:
  web:
    image: custom_portfolio
    container_name: portfolioContainer
    build: .
    ports:
      - '3001:3000'
    stdin_open : true
    tty: true
    develop:
      watch:
        - action: sync
          path : .
          target: /app
          ignore:
            - node_modules/